//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadianSampleTask
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UsersRegistrationEntities : DbContext
    {
        public UsersRegistrationEntities()
            : base("name=UsersRegistrationEntities")
        {
			this.Configuration.ProxyCreationEnabled = false;
		}
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<country> countries { get; set; }
        public virtual DbSet<State> States { get; set; }
    }
}
